version: '3'

services:
  nginx:
    container_name: dockerTest_nginx
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - nodejs-server
    command: nginx -g "daemon off";
    volumes:
      - ./containers/nginx:/etc/nginx/conf.d

  nodejs-server:
    container_name: dockerTest_nodejs
    build:
      context: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - redis-server
    command: yarn start
    volumes:
      - /home/ice013/Documents/Laptrinh/trynew/docker_node_nginx:/home/node/docker_node

  redis-server:
    container_name: dockerTest_redis
    image: redis:latest
    volumes:
      - /var/lib/redis:/data
